# Generated by Django 4.2.6 on 2023-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('placed_company', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
