# Generated by Django 4.2.6 on 2023-10-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='Student',
        ),
    ]
