# Generated by Django 4.2.6 on 2023-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_student_avatar_alter_student_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
