# Generated by Django 4.2.6 on 2023-10-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_student_avatar_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
