# Generated by Django 4.2.6 on 2024-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
