# Generated by Django 4.2.6 on 2024-01-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
