# Generated by Django 5.1.7 on 2025-04-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/avatar.svg', null=True, upload_to='static/images'),
        ),
    ]
